# Generated by Django 3.2.12 on 2022-03-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnciclaApp', '0002_auto_20220321_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
