# Generated by Django 3.2.13 on 2022-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnciclaApp', '0006_estacion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=30)),
                ('numeroDoc', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='estacion',
            name='image',
            field=models.CharField(default='css/images/floresta.jpg', max_length=200),
        ),
    ]
