# Generated by Django 3.2.13 on 2022-05-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnciclaApp', '0007_auto_20220525_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Id_type', models.CharField(max_length=100)),
                ('Id_number', models.CharField(max_length=30)),
                ('private_info', models.CharField(max_length=30)),
                ('disability', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=500)),
                ('id_contacto', models.CharField(max_length=30)),
            ],
        ),
    ]
